apiVersion: v1
entries:
  passwordstore:
  - apiVersion: v2
    appVersion: --version
    created: "2020-02-13T08:01:37.882300834Z"
    description: Passwordstore helm chart
    digest: 5e825e74eb6d0d984f2032beb527861da09d50b53f1773e06f3f57f354c7e88c
    name: passwordstore
    type: application
    urls:
    - passwordstore-0.7.2.tgz
    version: 0.7.2
generated: "2020-02-13T08:01:37.88112835Z"
